### ISSUE TITLE
Temp Control not working

### ISSUE THREAD

**Issue by sopalab** [synqs/DeviceControlServer#1]
Error message:
An error occured name 'tempcontrols' is not defined 
An unexpected error has occurred

**Comment by sopalab** [comment]
Here is the error message:
[2018-07-04 16:00:09,078] ERROR in app: Exception on /add_tempcontrol [GET]
Traceback (most recent call last):
  File "c:\users\lilo\appdata\local\conda\conda\envs\devicecontrolserver\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\lilo\appdata\local\conda\conda\envs\devicecontrolserver\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\lilo\appdata\local\conda\conda\envs\devicecontrolserver\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\lilo\appdata\local\conda\conda\envs\devicecontrolserver\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "c:\users\lilo\appdata\local\conda\conda\envs\devicecontrolserver\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\lilo\appdata\local\conda\conda\envs\devicecontrolserver\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\Lilo\Documents\GitHub\DeviceControlServer\app\thermocontrol\handlers.py", line 59, in add_tempcontrol
    n_ards = len(tempcontrols)
NameError: name 'tempcontrols' is not defined

**Comment by fretchen** [comment]
Closed in fbe1757
